import '~/styles/globals.css';

import {Poppins} from 'next/font/google';

import {TRPCReactProvider} from '~/trpc/react';
import Navbar from '~/components/Navbar';
import {ThemeProvider} from '~/components/theme-provider';
import {Toaster} from '~/components/ui/toaster';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{rel: 'icon', url: '/favicon.ico'}],
};

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className={poppins.className} suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="flex min-h-screen w-full">
              <Navbar />
              <div className="flex flex-1 items-center justify-center bg-darkPurple md:pl-[200px]">
                {children}
              </div>
              <Toaster />
            </main>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
